// all courses must be stored as an array of JSON objects to be passed to the VUE app
const lessons = [
    {
        "id": 101,
        "title": "Introduction to JavaScript",
        "level": "Beginner",
        "subject": "Programming",
        "location": "Online",
        "price": 100,
        "spaces": 2,
        "icon": "bi bi-book"
    },
    {
        "id": 102,
        "title": "Working with Arrays and Objects",
        "instructor": "Jane Smith",
        "duration": "1.5 hours",
        "level": "Intermediate",
        "subject": "Programming",
        "location": "Online",
        "price": 20,
        "spaces": 30,
        "icon": "bi bi-facebook"
    },
    {
        "id": 103,
        "title": "Asynchronous Programming with Promises",
        "instructor": "Mike Johnson",
        "duration": "2.5 hours",
        "level": "Intermediate",
        "subject": "Programming",
        "location": "In-Person",
        "price": 30,
        "spaces": 20,
        "rating": 5,
        "icon": "bi bi-pencil"
    },
    {
        "id": 104,
        "title": "React Basics",
        "instructor": "Sara Brown",
        "duration": "3 hours",
        "level": "Intermediate",
        "subject": "Web Development",
        "location": "Online",
        "price": 25,
        "spaces": 40,
        "rating": 5,
        "icon": "bi bi-facebook"
    },
    {
        "id": 105,
        "title": "Node.js Fundamentals",
        "instructor": "Chris Anderson",
        "duration": "2 hours",
        "level": "Intermediate",
        "subject": "Web Development",
        "location": "In-Person",
        "price": 30,
        "spaces": 15,
        "rating": 5,
        "icon": "bi bi-mortarboard"
    },
    {
        "id": 106,
        "title": "RESTful API Design",
        "instructor": "Alex Turner",
        "duration": "2.5 hours",
        "level": "Intermediate",
        "subject": "Web Development",
        "location": "Online",
        "price": 20,
        "spaces": 25,
        "rating": 5,
        "icon": "bi bi-speedometer2"
    },
    {
        "id": 107,
        "title": "Databases and SQL",
        "instructor": "Emily White",
        "duration": "2 hours",
        "level": "Intermediate",
        "subject": "Database",
        "location": "In-Person",
        "price": 25,
        "spaces": 20,
        "rating": 5,
        "icon": "bi bi-hospital"
    },
    {
        "id": 108,
        "title": "Advanced JavaScript Concepts",
        "instructor": "Daniel Rogers",
        "duration": "3 hours",
        "level": "Advanced",
        "subject": "Programming",
        "location": "Online",
        "price": 35,
        "spaces": 15,
        "rating": 5,
        "icon": "bi bi-bank"
    },
    {
        "id": 109,
        "title": "Web Development Best Practices",
        "instructor": "Olivia Taylor",
        "duration": "2.5 hours",
        "level": "Intermediate",
        "subject": "Web Development",
        "location": "In-Person",
        "price": 30,
        "spaces": 25,
        "rating": 5,
        "icon": "bi bi-shop"
    },
    {
        "id": 110,
        "title": "Introduction to Frontend Frameworks",
        "instructor": "Liam Davis",
        "duration": "2 hours",
        "level": "Intermediate",
        "subject": "Web Development",
        "location": "Online",
        "price": 20,
        "spaces": 30,
        "rating": 5,
        "icons": "bi bi-shop"
    },
];

// module.exports = lessons;
