// all courses must be stored as an array of JSON objects to be passed to the VUE app
const lessons = [
  {
    id: 101,
    title: "Introduction to JavaScript",
    subject: "Programming",
    location: "Online",
    price: 100,
    spaces: 5,
    icon: "bi bi-book",
  },
  {
    id: 102,
    title: "Working with Arrays and Objects",
    subject: "Programming",
    location: "Online",
    price: 20,
    spaces: 5,
    icon: "bi bi-facebook",
  },
  {
    id: 103,
    title: "Asynchronous Programming with Promises",
    subject: "Programming",
    location: "In-Person",
    price: 30,
    spaces: 5,
    icon: "bi bi-pencil",
  },
  {
    id: 104,
    title: 'React Basics',
    subject: "Web Development",
    location: "Online",
    price: 25,
    spaces: 5,
    icon: "bi bi-facebook",
  },
  {
    id: 105,
    title: "Node.js Fundamentals",
    subject: "Web Development",
    location: "In-Person",
    price: 30,
    spaces: 5,
    icon: "bi bi-mortarboard",
  },
  {
    id: 106,
    title: "RESTful API Design",
    subject: "Web Development",
    location: "Online",
    price: 20,
    spaces: 5,
    icon: "bi bi-speedometer2",
  },
  {
    id: 107,
    title: "Databases and SQL",
    subject: "Database",
    location: "In-Person",
    price: 25,
    spaces: 5,
    icon: "bi bi-hospital",
  },
  {
    id: 108,
    title: "Advanced JavaScript Concepts",
    subject: "Programming",
    location: "Online",
    price: 35,
    spaces: 5,
    icon: "bi bi-bank",
  },
  {
    id: 109,
    title: "Web Development Best Practices",
    subject: "Web Development",
    location: "In-Person",
    price: 30,
    spaces: 5,
    icon: "bi bi-shop",
  },
  {
    id: 110,
    title: "Introduction to Frontend Frameworks",
    subject: "Web Development",
    location: "Online",
    price: 20,
    spaces: 5,
    icons: "bi bi-shop",
  },
];

// module.exports = lessons;
